version: '3.3'
services:
  backend:
    build: .
    image: currency_converter-backend
    container_name: backend
    command: npm run start:dev
    volumes:
      - ./:/usr/app/backend/
    ports:
      - '8080:8080'
networks:
  default:
    driver: bridge
